## Publication settings

title: "The Title"
description: "The Description"
keywords: "a, whole, bunch, of, keywords"
date_format: "%b %-d, %Y" # for the table of contents
favicon: "img/favicon.ico"
social_image: "img/icon.png"

## Jekyll settings

exclude: [CNAME, README.md, .gitignore]
permalink: "#:title"
timezone: null
lsi: false
markdown: kramdown
kramdown:
  auto_ids: false
  footnote_backlink: #nope
plugins:
  - jekyll-feed
collections:
  - pages
